"""add archived_at to job_posting

Revision ID: 512305660739
Revises: b50dd45e7871
Create Date: 2026-04-05 22:42:03.905783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512305660739'
down_revision: Union[str, None] = 'b50dd45e7871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posting', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('job_posting', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_posting', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('job_posting', 'archived_at')
    # ### end Alembic commands ###