"""add new column to user

Revision ID: b50dd45e7871
Revises: 4e9f1d40e9d7
Create Date: 2026-04-03 13:42:06.278396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50dd45e7871'
down_revision: Union[str, None] = '4e9f1d40e9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posting', sa.Column('created_by_id', sa.UUID(), nullable=True))
    op.add_column('job_posting', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_foreign_key(None, 'job_posting', 'user', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_parsing_job_status', table_name='parsing_job')
    op.drop_index('ix_resume_extraction_application_id', table_name='resume_extraction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_resume_extraction_application_id', 'resume_extraction', ['application_id'], unique=False)
    op.create_index('ix_parsing_job_status', 'parsing_job', ['status'], unique=False)
    op.drop_constraint(None, 'job_posting', type_='foreignkey')
    op.drop_column('job_posting', 'updated_at')
    op.drop_column('job_posting', 'created_by_id')
    # ### end Alembic commands ###